package una.paradigmas;

import org.junit.Test;

import una.paradigmas.ast.AstBuilder;
import una.paradigmas.ast.AstPrintVisitor;
import una.paradigmas.ast.ExpressoLexer;
import una.paradigmas.ast.ExpressoParser;
import una.paradigmas.ast.Program;


import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

/**
 * Proyecto: Expresso - Transpilador de lenguaje Expresso a Java
 * Curso: [EIF400-II-2025] Paradigmas de Programacion
 * Universidad Nacional de Costa Rica
 * 
 * Autores:
 * - Kendall Miso Chinchilla Araya  -   119310542
 * - Ignacio Serrano Gonzalez       -   402600631
 * - Minor Brenes Aguilar           -   116730106
 * - Pablo Chavarria Alvarez        -   117810573
 * 
 * Codigo de grupo: 02-1PM
 * 
 * This source file was generated by the Gradle 'init' task
 */

public class AppTest {
    @Test 
public void testAST() {
        String input = "let x = 666\n" +
                        "print(x)\n" +
                        "let y = 10\n" +
                        "print(y)\n" +
                        "let f = z -> z ** 2 + 2 * z + 1\n" +
                        "print(f(x) + f(y))";

        CharStream charStream = CharStreams.fromString(input);
        ExpressoLexer lexer = new ExpressoLexer(charStream);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        ExpressoParser parser = new ExpressoParser(tokens);

        //parsear y construir AST
        AstBuilder builder = new AstBuilder();
        Program ast = builder.visitProgram(parser.program());

        // imprimir con print visitor
        AstPrintVisitor printer = new AstPrintVisitor();
        printer.visitProgram(ast);
    }

}