package una.paradigmas;

import org.junit.Test;

import una.paradigmas.ast.AstBuilder;
// import una.paradigmas.ast.AstPrintVisitor;
import una.paradigmas.ast.ExpressoLexer;
import una.paradigmas.ast.ExpressoParser;
import una.paradigmas.ast.JavaCodeGenerator;
import una.paradigmas.node.Program;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

 /**
 * Proyecto: Expresso - Transpilador de lenguaje Expresso a Java
 * Curso: [EIF400-II-2025] Paradigmas de Programacion
 * Universidad Nacional de Costa Rica
 * 
 * Autores:
 * - Kendall Miso Chinchilla Araya  -   119310542
 * - Ignacio Serrano Gonzalez       -   402600631
 * - Minor Brenes Aguilar           -   116730106
 * - Pablo Chavarria Alvarez        -   117810573
 * 
 * Codigo de grupo: 02-1PM
 * 
 * This source file was generated by the Gradle 'init' task
 * 
 * Nota: Este codigo fue generado parcialmente con asistencia de IA
 * y posteriormente modificado, adaptado y validado por el equipo
 * de desarrollo para cumplir con los requerimientos especificos
 * del proyecto.
 */

 public class AppTest {
    
    private void testExpressoProgram(String input, String className) {
        CharStream charStream = CharStreams.fromString(input);
        ExpressoLexer lexer = new ExpressoLexer(charStream);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        ExpressoParser parser = new ExpressoParser(tokens);

        // Parsear y construir AST
        AstBuilder builder = new AstBuilder();
        Program ast = builder.visitProgram(parser.program());

        // Imprimir con print visitor
        // AstPrintVisitor printer = new AstPrintVisitor();
        // printer.visitProgram(ast);

        // Generar codigo Java a partir del AST
        JavaCodeGenerator generator = new JavaCodeGenerator(className);
        String javaCode = generator.generate(ast);
        System.out.println("\n");
        System.out.println(javaCode);
    }

    @Test 
    public void testHelloWorld0() {

        System.out.println("====== Test HelloWorld0.expresso ======");
                      
        String input = "// HelloWorld0.expresso\n" +
                      "let x = 666\n" +
                      "print(x) // Expected 666 in console\n" +
                      "let y = 10\n" +
                      "print(y) // Expected 10 in console\n" +
                      "let f = z -> z ** 2 + 2*z + 1\n" +
                      "print(f(x) + f(y)) // expected 445010\n";
        
        testExpressoProgram(input, "HelloWorld0");
    }

    @Test 
    public void testHelloWorld1() {

        System.out.println("====== Test HelloWorld1.expresso ======");

        String input = "// HelloWorld1.expresso\n\n" +
                      "/*\n" +
                      "  As HelloWorld0 but with a Binary Function\n" +
                      "  @author hooNous\n" +
                      "  @since Oct 6th, 2025\n" +
                      "*/\n\n" +
                      "let x = 6\n" +
                      "print(x)\n" +
                      "let y = 3\n" +
                      "print(y)\n" +
                      "let f = (w, z) -> z ** w + w*z + 1\n" +
                      "print(f(x, y)) // Expected 748\n";
        
        testExpressoProgram(input, "HelloWorld1");
    }

    @Test 
    public void testHelloWorld2() {

        System.out.println("====== Test HelloWorld2.expresso ======");

        String input = "// HelloWorld2.expresso\n\n" +
                      "/*\n" +
                      "  Boolean Logic\n" +
                      "  @author hooNous\n" +
                      "  @since Oct 6th, 2025\n" +
                      "*/\n\n" +
                      "let isZero = x -> x ? 0 : 1\n" +
                      "let TRUE  = 1\n" +
                      "let FALSE = 0\n\n" +
                      "let isTrue = x -> isZero(x) ? FALSE : TRUE\n\n" +
                      "let NOT = x -> x ? 0 : 1\n\n" +
                      "let OR =  (x, y) -> isTrue(x) ? TRUE : isTrue(y)\n\n" +
                      "let AND = (x, y) -> isTrue(x) ? isTrue(y) : FALSE\n\n" +
                      "let XOR = (x, y) -> AND(OR(x, y), NOT(AND(x, y)))\n\n" +
                      "print(XOR(TRUE, TRUE))   // Expected 0\n" +
                      "print(XOR(TRUE, FALSE))  // Expected 1\n" +
                      "print(XOR(FALSE, TRUE))  // Expected 1\n" +
                      "print(XOR(FALSE, FALSE)) // Expected 0\n";
        
        testExpressoProgram(input, "HelloWorld2");
    }

    // @Test 
    // public void testHelloWorld3() {

    //     System.out.println("====== Test HelloWorld3.expresso ======");
    //     System.out.println("====== Devil's surprises ======");

    //     String input = "/* HelloWorld3.expresso */\n" +
    //                     "\n" +
    //                     "/*\n" +
    //                     "  Devil's suprises\n" +
    //                     "  @author hooNous\n" +
    //                     "  @since Oct 6th, 2025\n" +
    //                     "*/\n" +
    //                     "\n" +
    //                     "/*\n" +
    //                     "Expected output:\n" +
    //                     "111\n" +
    //                     "1\n" +
    //                     "12\n" +
    //                     "222\n" +
    //                     "666\n" +
    //                     "12\n" +
    //                     "444\n" +
    //                     "0\n" +
    //                     "1\n" +
    //                     "555\n" +
    //                     "-666\n" +
    //                     "999\n" +
    //                     "*/\n" +
    //                     "\n" +
    //                     "/////////////////////////////////////////////////\n" +
    //                     "//# Section 111\n" +
    //                     "print(111)\n" +
    //                     "print(666 ? 1 : 2 + 10) // Expecting 1\n" +
    //                     "print(0 ? 1 : 2 + 10)   // Expecting 12\n" +
    //                     "\n" +
    //                     "/////////////////////////////////////////////////\n" +
    //                     "//# Section 222\n" +
    //                     "print(222)\n" +
    //                     "print( 0 ? 0 ? 1 : 2 + 10 : 666) // Expecting 666\n" +
    //                     "\n" +
    //                     "print( 1 ? 0 ? 1 : 2 + 10 : 666) // Expecting 12\n" +
    //                     "\n" +
    //                     "/////////////////////////////////////////////////\n" +
    //                     "//# Section 333\n" +
    //                     "/* ?: multiline */ \n" +
    //                     "let isZero = x -> x ? 0  : 1\n" +
    //                     "\n" +
    //                     "\n" +
    //                     "/* const */ let  TRUE  = /* */ 1\n" +
    //                     "/* const */ let  FALSE = 0\n" +
    //                     "\n" +
    //                     "/////////////////////////////////////////////////\n" +
    //                     "//# Section 444\n" +
    //                     "print(444)\n" +
    //                     "let mod_2 = x -> x - x / 2 * 2 \n" +
    //                     "\n" +
    //                     "print(mod_2(666))    // Expecting 0\n" +
    //                     "print(mod_2(666 +1)) // Expecting 1\n" +
    //                     "\n" +
    //                     "/////////////////////////////////////////////////\n" +
    //                     "//# Section 444\n" +
    //                     "print(555)\n" +
    //                     "\n" +
    //                     "let _hasUnderscores_ = -666 // must be parsed\n" +
    //                     "print(_hasUnderscores_)  // Expecting -666\n" + // falta resolver conflicto con PostOp
    //                     "\n" +
    //                     "/////////////////////////////////////////////////\n" +
    //                     "//# Section 999\n" +
    //                     "print(999)\n" +
    //                     "// print(variable_not_defined) // Expecting to be transpiled but not built";
        
    //     testExpressoProgram(input, "HelloWorld3");
    // }

    @Test 
    public void testHelloWorld4() {

        System.out.println("====== Test HelloWorld4.expresso ======");
        System.out.println("Tarea 13 - Tipos float-boolean-string-any");
                      
        String input = """
            let msg = "Hello \\"World\\""
            let x:float = 3.14
            let y = 666
            let b = true
            let s = "hello"
            print(x + 2.0 + y)
            print(s)
            print(b)
        """;
        
        testExpressoProgram(input, "HelloWorld4");
    }
    
    @Test 
    public void testHelloWorld5() {

        System.out.println("====== Test HelloWorld5.expresso ======");
        System.out.println("Tarea 14 - fun");
                      
        String input = """
            fun fact(n:int):int = n ? n * fact(n - 1) : 1
            """;
            
        testExpressoProgram(input, "HelloWorld5");
    }
    
    @Test 
    public void testHelloWorld6() {
    System.out.println("====== Test HelloWorld6.expresso ======");
    
    String input = "data nat = { Zero, S(n:nat) }\n" +
                   "data list = { Nil, Cons(car:any, cdr:list) }\n" +
                   "data gender = { Male, Female }\n" +
                   "let x = 666\n" +
                   "print(x)\n";
    
    testExpressoProgram(input, "HelloWorld6");
    }

    @Test
    public void testConstructorInvocation() {
        System.out.println("====== Test ConstructorInvocation.expresso ======");
        System.out.println("Tarea 17 - Soporte para el operador ^");

        String input = """
            data list = { Nil, Cons(car:any, cdr:list) }
            let x = ^Nil
            let y = ^Cons(666, ^Nil)
            print(y)
        """;

        testExpressoProgram(input, "ConstructorInvocation");
    }

        @Test
    public void testArrowsAndTuples() {
        System.out.println("====== Test Arrows and Tuples ======");
        
        String input = 
            // Función con tipo arrow simple: int -> int
            "fun double(x: int): int = x * 2\n" +
            
            // Función con tipo arrow compuesto: int -> int -> int
            "fun add(x: int): int -> int = y -> x + y\n" +
            
            // Función con tuple como parámetro: (int, int) -> int
            "fun sumPair(pair: (int, int)): int = 0\n" +
            
            // Función con arrow complejo: (int, int) -> int -> int
            "fun complex(pair: (int, int)): int -> int = x -> x + 1\n" +
            
            // Función con multiple arrows: int -> (int -> int)
            "fun curry(x: int): (int -> int) = y -> x + y\n" +
            
            // Función con tuple de arrows: (int -> int, int -> int) -> int
            "fun applyBoth(fns: (int -> int, int -> int)): int = 0\n" +
            
            // Lambda con tipo inferido
            "let increment = x -> x + 1\n" +
            
            // Usar las funciones
            "let result1 = double(5)\n" +
            "print(result1)\n" +
            
            "let result2 = add(3)\n" +
            "let result3 = result2(7)\n" +
            "print(result3)\n" +
            
            "let inc = increment\n" +
            "print(inc(10))\n";
        
        testExpressoProgram(input, "ArrowsAndTuples");
    }

    @Test
    public void testMatchExpression() {
        System.out.println("====== Test Match Expression ======");
        
        String input = 
            "data List = { Nil, Cons(head: int, tail: List) }\n" +
            
            // Una línea por función
            "fun length(list: List): int = match list with Nil -> 0 | Cons(_, tail) -> 1 + length(tail)\n" +
            
            "fun sum(list: List): int = match list with Nil -> 0 | Cons(h, t) -> h + sum(t)\n" +
            
            "fun describe(n: int): string = match n with 0 -> \"zero\" | 1 -> \"one\" | _ -> \"many\"\n" +
            
            "let empty = ^Nil\n" +
            "let list1 = ^Cons(5, ^Nil)\n" +
            "let list2 = ^Cons(3, ^Cons(7, ^Nil))\n" +
            
            "print(length(empty))\n" +
            "print(length(list1))\n" +
            "print(length(list2))\n" +
            "print(sum(list2))\n" +
            "print(describe(0))\n" +
            "print(describe(1))\n" +
            "print(describe(42))\n";
        
        testExpressoProgram(input, "MatchExpression");
    }

    @Test
    public void testAdvancedMatch() {
        System.out.println("====== Test Advanced Match ======");
        
        String input = 
            "data Option = { None, Some(value: int) }\n" +
            
            "fun getOrDefault(opt: Option): int = match opt with None -> -1 | Some(v) -> v\n" +
            
            "data Tree = { Leaf, Node(left: Tree, value: int, right: Tree) }\n" +
            
            "fun getRoot(tree: Tree): int = match tree with Leaf -> 0 | Node(_, v, _) -> v\n" +
            
            "fun boolToInt(b: boolean): int = match b with true -> 1 | false -> 0\n" +
            
            "let none = ^None\n" +
            "let some5 = ^Some(5)\n" +
            "print(getOrDefault(none))\n" +
            "print(getOrDefault(some5))\n" +
            
            "let leaf = ^Leaf\n" +
            "let node = ^Node(^Leaf, 42, ^Leaf)\n" +
            "print(getRoot(leaf))\n" +
            "print(getRoot(node))\n" +
            
            "print(boolToInt(true))\n" +
            "print(boolToInt(false))\n";
        
        testExpressoProgram(input, "AdvancedMatch");
    }

    @Test
    public void testCombinedFeatures() {
        System.out.println("====== Test Combined Features ======");
        
        String input = 
            "data List = { Nil, Cons(head: int, tail: List) }\n" +
            
            "fun double(x: int): int = x * 2\n" +
            
            "fun length(list: List): int = match list with Nil -> 0 | Cons(_, t) -> 1 + length(t)\n" +
            
            "let nums = ^Cons(1, ^Cons(2, ^Cons(3, ^Nil)))\n" +
            
            "print(length(nums))\n" +
            "print(double(5))\n";
        
        testExpressoProgram(input, "CombinedFeatures");
    }

}